### ISSUE TITLE
Spells and non-static abilities that care whether a permanent is enchanted, will see equipped permanent as enchanted

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#535] opened 2018-06-12 18:53 UTC
**What is the expected behaviour of the card?**
 - Equipped isn't the same as Enchanted

**What is the actual behaviour of the card?**
 - The system will see equipped permanents as enchanted. This issue for advantageous bugged cards

**Screenshot**
[2018-06-13 part 1](https://youtu.be/UnhUsWP2Lk4)
[2018-06-13 part 2](https://youtu.be/d7aH9j3iJOk)

**Please provide a list of affected cards**
Affects: [Dreampod Druid][Krond the Dawn-Clad]

**Card Images**

 <img src="https://pennydreadfulmagic.com/image/Dreampod%20Druid|Krond%20the%20Dawn-Clad/" height="300px">

**Comment by Rowsol** [comment] 2018-06-12 18:54
I'm aware there's no proof of being enchanted.  If need be I can access the replay and make a video.

**Comment by stash86** [comment] 2018-06-13 08:52
Update the description. Add more affected cards and videos

**Comment by BackAlleyG** [comment] 2018-07-12 00:42
Duplicate of #532

**Comment by stash86** [comment] 2018-07-12 01:30
Reopen this issue because only they only fix #532

**Comment by stash86** [comment] 2019-11-30 01:48
Still bugged

![image](https://user-images.githubusercontent.com/13656154/69894151-eea70c00-135e-11ea-8a75-992e7c8bce22.png)

**Comment by stash86** [comment] 2020-02-26 07:32
Still bugged. I guess they only fix standard legal cards, and doesn't care about old cards, because according to the latest build notes

Certain effects that target creatures that are enchanted, such as the triggered ability of Nyx Herald, are correctly no longer able to target creatures that are equipped.

**Comment by stash86** [comment] 2020-02-27 06:37
Almost all fixed. 2 left

**Closed** 2021-10-17 09:10 UTC
Labels: Advantageous, Has Video
