### ISSUE TITLE
Hagra Mauling appears to trigger the MTGO Game Restart Bug

### ISSUE THREAD

**Issue by shdwcat** [PennyDreadfulMTG/modo-bugs#913] opened 2021-04-29 06:05 UTC
**What is the expected behaviour of the card?**
 - Not trigger the MTGO Game Restart Bug

**What is the actual behaviour of the card?**
 - Appears to trigger the MTGO Game Restart Bug. It happened to me 3 or 4 times today, where some amount of time after casting Hagra Mauling, MTGO would start replaying the game. That was the only constant across all the times it triggered

**Screenshot**
Sorry didn't think to grab one

**Please provide a list of affected cards**
Affects: Hagra Mauling

**Card Images**

**Comment by jmeka** [comment] 2021-04-30 17:54
This is hard to replicate as the initial description is a bit vague. I was able to cast Hagra Mauling on my own with little resistance. Please try to elaborate the specifics of this "bug."

**Comment by nex3** [comment] 2021-04-30 19:04
The catual behavior was kind of vague as well. The consistent factor was that Hagra Mauling was cast, and then some time afterwards—often several turns more—the game would go into a restart loop and eventually crash.

**Comment by Kalioc** [comment] 2021-05-12 16:06
I'm closing this since there isn't any way to reproduce this with specifics or a screenshot to go off of. 
It's like something else in the game likely caused the restart bug.

**Closed by Kalioc** 2021-05-12 16:06 UTC
Labels: Needs Screenshot, Unclassified

**Comment by nex3** [comment] 2021-05-13 23:40
We got some more experience with this during our cube session last night. The bug is not very consistent and very difficult to reproduce, but what we know is:

* Decks that contain Hagra Mauling seem to be experiencing many MTGO restarts.
* Casting Hagra Mauling doesn't seem to be closely associated with the bug. In one instance, the restart happened several turns after it was cast. In another (the source of the screenshot below), it was merely in hand when the game restarted.
* Sometimes an entire game finishes without any restarts at all.
* When the player moved Hagra Mauling from his maindeck to his sideboard, we saw no more restarts.

I understand that it's hard to verify and track a bug that's this difficult to reproduce, but I'm convinced enough that Hagra Mauling is the culprit here that I'm removing it from my cube for the time being.
