### ISSUE TITLE
Austere Command does not respect 711.4b and treats the back face of double-faced cards as having a converted mana cost of 0.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#439] opened 2018-04-10 07:40 UTC
From Bug Blog.
Affects: 

Bug Blog Text: [Austere Command] does not respect 711.4b and treats the back face of double-faced cards as having a converted mana cost of 0.

**Comment by BackAlleyG** [comment] 2018-04-11 03:01
Duplicate of #258

**Closed by BackAlleyG** 2018-04-11 03:01 UTC
Labels: From Bug Blog, Unclassified, duplicate
