### ISSUE TITLE
Redirecting spells and abilities sometimes restarts the game in a buggy state

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#246] opened 2018-01-02 08:41 UTC
![image](https://user-images.githubusercontent.com/194254/34478384-d48b3952-eff4-11e7-89c1-346e4552c96f.png)
Affects: [Imp's Mischief], [Misdirection], [Swerve], [Wild Ricochet], [Shunt], [Deflection], [Reroute]
 <img src="https://api.scryfall.com/cards/named?exact=Imp%27s%20Mischief&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Misdirection&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Swerve&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Wild%20Ricochet&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Shunt&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Deflection&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Reroute&format=image" width="200px">

**Comment by BackAlleyG** [comment] 2018-01-15 00:14
Also effects [Swerve]. Happened a while ago so I don't have a game log to take a picture of but it was when my opponent targeted a cruel ultimatum which doesn't actually accomplish anything normally.

**Comment by silasary** [comment] 2018-01-15 00:18
Hypothesis: When redirecting, MTGO evaluates possible targets as though you were the controller.  It then realizes that the chosen player isn't a valid target, and resets the game due to checksum failure.

**Comment by silasary** [comment] 2018-01-18 00:13
Hypothesis disproven:  Wild Ricochet targetting Act of Agression restarted the game.

**Comment by jmeka** [comment] 2018-01-24 17:56
https://youtu.be/WZvQEFyJbbs

**Comment by jmeka** [comment] 2018-01-24 20:04
Also affects [shunt] [deflection]

**Comment by NARFNra** [comment] 2018-02-03 09:50
Has this ever been seen to occur with abilities that redirect targets without giving a choice as to the target? e.g.
Spellskite, Muck Drubb?

**Comment by silasary** [comment] 2018-02-03 10:52
No, only cards that ask you to choose a new target.

**Comment by BackAlleyG** [comment] 2018-03-19 20:21
Fixed in build notes of [March 13 announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-march-13-2018).

Also did some extensive testing with no game restarts so seems to be fixed along with #146 which I guess this was a duplicate of sort of but anyways closing that one too!

**Closed by BackAlleyG** 2018-03-19 20:21 UTC
Labels: Affects PD, Game Breaking
