### ISSUE TITLE
Charging Tuskodon deals double damage to a player when targeted by Form of the Dinosaur.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#440] opened 2018-04-10 07:42 UTC
From Bug Blog.
Affects: 

Bug Blog Text: [Charging Tuskodon] deals double damage to a player when targeted by [Form of the Dinosaur].

**Comment by BackAlleyG** [comment] 2018-04-11 02:56
Duplicate of #286

**Closed by BackAlleyG** 2018-04-11 02:56 UTC
Labels: From Bug Blog, Unclassified, duplicate
