### ISSUE TITLE
Tawnos's Coffin possibly fixed?

### ISSUE THREAD

**Issue by zinnerzPT** [PennyDreadfulMTG/modo-bugs#470] opened 2018-05-04 10:47 UTC
**What is the expected behaviour of the card?**
 - The card exiles a creature and auras enchanted to it, and when it untaps, it returns the exiled creature to its owner's controller with the auras still attached.

**What is the actual behaviour of the card?**
 - On solitaire mode, the card worked as intended. But requires further testing against actual opponents.

**Screenshot**
![image](https://user-images.githubusercontent.com/2437964/39624296-b2c3b596-4f90-11e8-9d59-da4ff24743eb.png)

**Please provide a list of affected cards**
Affects: [Tawnos's Coffin]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by silasary** [comment] 2018-05-04 11:09
Duplicate of #40

**Closed by silasary** 2018-05-04 11:09 UTC
