### ISSUE TITLE
[Sorcerous Spyglass] crashes MTGO upon reviewing the game

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/modo-bugs#211] opened 2017-10-30 02:45 UTC
Reported on Discord by PsyMar#2210

https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/issues/1442

**Comment by silasary** [comment] 2017-10-31 04:02
Duplicate of #212

**Closed by silasary** 2017-10-31 04:02 UTC
Labels: Unclassified
