### ISSUE TITLE
Death's Shadow can become larger than 13/13 and does not respect the recent rules change to 107.1b

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#436] opened 2018-04-10 07:32 UTC
From Bug Blog.
Affects: 

Bug Blog Text: [Death's Shadow] can become larger than 13/13 and does not respect the recent rules change to 107.1b

**Comment by BackAlleyG** [comment] 2018-04-11 17:25
Duplicate of #257

**Closed by BackAlleyG** 2018-04-11 17:25 UTC
Labels: From Bug Blog, duplicate
