### ISSUE TITLE
"Far / Away" using Fuse effect resets the game

### ISSUE THREAD

**Issue by mdkangas** [PennyDreadfulMTG/modo-bugs#549] opened 2018-07-10 16:32 UTC
**What is the expected behaviour of the card?**
 - when using Fuse, choose creature to bounce and player to sac a creature

**What is the actual behaviour of the card?**
 - Far and Away can be used properly if done independently. if you Fuse, it full resets the game. (with a ton of animation in between)

**Screenshot**
no screenshot to show. it's a brand new game.

**Please provide a list of affected cards**
Affects: [Card Name](, [Second Card name], etc)
Fuse Far/Away.
Far = bounce a target creature for 1U
Away = target player sac creature for 2B

**Card Images**
Far / Away
 <img src="http://magic.bluebones.net/proxies/index2.php?c=Card%20Name|Second%20Card%20name" height="300px">

**Comment by silasary** [comment] 2018-07-11 03:55
Duplicate of #543

**Closed by silasary** 2018-07-11 03:55 UTC
Labels: Invalid Card Name, Needs Screenshot, Unclassified
