### ISSUE TITLE
Ixalan's Binding does not prevent cards with the same name from being cast

### ISSUE THREAD

**Issue by rshipskind** [PennyDreadfulMTG/modo-bugs#999] opened 2022-01-21 22:08 UTC
**What is the expected behaviour of the card?**
 - Cards that share a name with the exiled card cannot be cast

**What is the actual behaviour of the card?**
 - A card with delve and the same name as the exiled card, drawn after Ixalan's Binding entered play can be cast 

**Screenshot**
![ixalansbinding](https://user-images.githubusercontent.com/10050903/150606387-a1a8a3af-0b98-4c10-9a84-25a0d0936dac.JPG)

**Please provide a list of affected cards**
Affects: Ixalan's Binding

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by MultiDragon** [comment] 2022-01-21 22:10
duplicate of #926

**Closed by MultiDragon** 2022-01-21 22:10 UTC
Labels: Disadvantageous
