### ISSUE TITLE
Frogify doesn't strip certain effects

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#985] opened 2021-12-20 22:48 UTC
**What is the expected behaviour of the card?**
 - creature loses all abilities

**What is the actual behaviour of the card?**
 - it loses most abilities.

**Explanation**
I used it on my opponent's [Mephidross Vampire]. It retained it's ability to give other creatures +1 counters.

**Please provide a list of affected cards**
Affects: [Frogify]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Frogify/" height="300px">
![Screenshot (240)](https://user-images.githubusercontent.com/35880360/146842800-6f60e9fe-5927-4588-9d8a-003bedee711e.png)

**Comment by MultiDragon** [comment] 2021-12-20 22:57
I think due to how layers work, this is not a bug. Similarly to oko and Magus of the moon

**Comment by Kalioc** [comment] 2021-12-21 00:09
Going to close this because I'm also pretty sure this is just **_L A Y E R S_**. 🧙
Vampire on 3; Frogify on 6.

**Closed by Kalioc** 2021-12-21 00:09 UTC
Labels: Unclassified, Has Screenshot, Needs Video
