### ISSUE TITLE
When Blood Moon is in play, you are incorrectly prompted to name creature types for lands that require you to name one as they enter the battlefield.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#432] opened 2018-04-10 07:23 UTC
From Bug Blog.
Affects: 

Bug Blog Text: When [Blood Moon] is in play, you are incorrectly prompted to name creature types for lands that require you to name one as they enter the battlefield.

**Comment by BackAlleyG** [comment] 2018-04-11 17:39
Duplicate of #270

**Closed by BackAlleyG** 2018-04-11 17:39 UTC
Labels: From Bug Blog, duplicate
