### ISSUE TITLE
After copying a spell for each other object it could target, the game often resets in a buggy state

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#152] opened 2017-08-16 18:19 UTC
Still trying to figure out specifically  what kind of spells can cause this. Originally happended with a flashbacked Devil's Play targeting a precursor golem. I've found it happens with similar creates like Zada, Hedron Grinder, Mirrorwing dragon, and Ink-treader nephlim but haven't figured out what is the specific aspect of certain spells that cause the reset.
Affects: [Precursor Golem], [Zada, Hedron Grinder]
 <img src="https://api.scryfall.com/cards/named?exact=Precursor%20Golem&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Zada%2C%20Hedron%20Grinder&format=image" width="200px">

**Comment by silasary** [comment] 2017-10-06 05:16
Couldn't reproduce, Feel free to reopen with more details if it happens again.

**Comment by BackAlleyG** [comment] 2018-01-21 22:15
Happened again so reopening. It happened to me during PDSaturdays 7.01 in round 3 vs Gliffendoor with a precursor golem. Pdbot doesn't have the log for the game though so no solid proof sadly and my logs only show the game after it was restarted. I'll try again at some point. Seems to only happen sometimes and maybe has the same or a similar cause of #246

**Comment by silasary** [comment] 2018-01-23 02:43
Happened again today with a golem.  Game sucessfully recovered.

**Comment by jmeka** [comment] 2018-01-23 05:22
https://youtu.be/DCgUs_-tohs

So it seems like if you don't outright kill the Precursor and it's friends, bad things happen. I haven't tried buffing it yet or anything.

**Comment by mmrsad** [comment] 2018-01-29 19:24
Happened today with a Volcanic Hammer on Precursor Golem.

After Volcanic Hammer was played, all cards on screen bugged and flew around in many directions. I turned on capture after that and got the game restart.  

https://gfycat.com/ComposedValidGerbil

**Comment by jmeka** [comment] 2018-02-02 07:12
Just for fun, the Zada video: https://youtu.be/j2zavToB0N0

**Comment by Pixywing** [comment] 2018-03-15 03:04
Golems appears to currently be working. Tested exile, destroy, lethal damage, non-lethal damage, act of treason type effects, spells that targeted two creatures (prey upon), pump effects, and -1/-1 counter effects and couldn't get golems to break. 

https://youtu.be/LHFmG7i_MN8

**Comment by stash86** [comment] 2018-03-15 03:37
Just tested Zada as well, no game reset happened. So I'm closing this issue and unban them untul proven otherwise

**Closed by stash86** 2018-03-15 03:37 UTC
Labels: Affects PD, Game Breaking
