### ISSUE TITLE
Kamigawa Flip cards such as Stabwhisker the Odious are displayed as enchantments and do not respect the attack with all function or changes to power and toughness. Workaround: Click the creature separately to attack with it, and right click the creature to display its correct power and toughness.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#437] opened 2018-04-10 07:34 UTC
From Bug Blog.
Affects: 

Bug Blog Text: Kamigawa Flip cards such as [Stabwhisker the Odious] are displayed as enchantments and do not respect the attack with all function or changes to power and toughness. Workaround: Click the creature separately to attack with it, and right click the creature to display its correct power and toughness.

**Comment by BackAlleyG** [comment] 2018-04-11 17:56
Duplicate of #259

**Closed by BackAlleyG** 2018-04-11 17:56 UTC
Labels: From Bug Blog, duplicate
