### ISSUE TITLE
Swirl the Mists will randomly restart the game

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#848] opened 2020-05-28 08:59 UTC
Still can't pinpoint the exact trigger for the restart.

**What is the expected behaviour of the card?**

**What is the actual behaviour of the card?**

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Swirl the Mists]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Swirl%20the%20Mists/" height="300px">

**Comment by silasary** [comment] 2022-01-14 02:04
Duplicate of #708

**Closed by silasary** 2022-01-14 02:04 UTC
Labels: Needs Screenshot, Disadvantageous, Game Breaking
