### ISSUE TITLE
Split cards are unable to be cast through the Hideaway Lands fromLorwynsuch as Shelldock Isle.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#434] opened 2018-04-10 07:27 UTC
From Bug Blog.
Affects: 

Bug Blog Text: Split cards are unable to be cast through the Hideaway Lands fromLorwynsuch as [Shelldock Isle].

**Comment by BackAlleyG** [comment] 2018-04-11 17:32
Duplicate of #273

**Closed by BackAlleyG** 2018-04-11 17:32 UTC
Labels: From Bug Blog, Unclassified
