### ISSUE TITLE
Blood Clock bug

### ISSUE THREAD

**Issue by Harry-Truman** [PennyDreadfulMTG/modo-bugs#865] opened 2020-10-07 21:09 UTC
**What is the expected behaviour of the card?**
 Every upkeep, you choose between returning a permanent you control to hand and losing to life.

**What is the actual behaviour of the card?**
 Every upkeep, it asks you if you want to lose 2 life. If you pick yes, you lose 2 life. If you pick no, it asks you again. Clicking permanents you control does nothing. Therefore, Blood Clock (potentially advantageously or disadvantageously) only drains 2 life each turn with no other effect.

**Screenshot**
https://i.imgur.com/LM8tlWY.png

**Please provide a list of affected cards**
Affects: [Blood Clock]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Blood%20Clock/" height="300px">

**Comment by silasary** [comment] 2020-10-08 10:15
Duplicate of #864

**Closed by silasary** 2020-10-08 10:15 UTC
Labels: Has Screenshot, Needs Video, Unclassified
