### ISSUE TITLE
Kaya's Ghostform just doesn't seem to work.

### ISSUE THREAD

**Issue by Nosliw87** [PennyDreadfulMTG/modo-bugs#903] opened 2021-03-06 20:45 UTC
**What is the expected behaviour of the card?**
 - When enchanted creature dies or is put into exile, return it back to the battlefield under your control

**What is the actual behaviour of the card?**
 - Your creature dies and nothing happens and you are sad. At least during combat.

**Screenshot**
![MTGO_2021-03-06_15-36-45](https://user-images.githubusercontent.com/80176184/110220298-a8f6be80-7e92-11eb-992a-10dcd96b12d4.png)

**Please provide a list of affected cards**
Affects [Kaya's Ghostform] 

**Card Images**
 

Affects:

**Comment by Kalioc** [comment] 2021-06-19 12:36
Videos from a duplicate of this issue.
https://youtu.be/yXI29ZE_rkQ
https://youtu.be/EIDD_4KVDSU

**Comment by datrobino** [comment] 2024-09-04 12:12
fixed

**Closed by datrobino** 2024-09-04 12:12 UTC
Labels: Non-Functional ability, Has Screenshot, Needs Video, Needs Forum Post
