### ISSUE TITLE
Splicing [Glacial Ray] onto another Arcane spell restarts the game

### ISSUE THREAD

**Issue by Kazaxat** [PennyDreadfulMTG/modo-bugs#253] opened 2018-01-08 15:08 UTC
**What is the expected behaviour of the card?**
 - Glacial Ray should add it's 2 damage effect to the other arcane spell when spliced.

**What is the actual behaviour of the card?**
 - If you attempt to splice Glacial Ray onto another Arcane spell the game bugs out and restarts.

**Screenshot**
(Attach a screenshot or video here)
![image](https://user-images.githubusercontent.com/28510571/34676706-bf8a0f90-f45b-11e7-93a9-388d4297f5a3.png)

**Please provide a list of affected cards**
Affects: [Glacial Ray]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Glacial%20Ray&format=image" width="300px">

**Comment by silasary** [comment] 2018-01-08 15:40
Duplicate of #142

**Comment by silasary** [comment] 2018-01-11 04:36
Fixed in [Jan 9 Build Notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-january-9-2018#_Build_Notes)

**Closed by silasary** 2018-01-11 04:36 UTC
Labels: Affects PD, Unclassified
