### ISSUE TITLE
If [Yisan, the Wanderer Bard's] verse counters are removed in response to its ability, you are still able to search your library for a creature with converted mana cost equal to the initial number of counters.

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#275] opened 2018-01-15 03:41 UTC
From Bug Blog 

Affects: [Yisan, the Wanderer Bard]

**Card Images**

**Comment by silasary** [comment] 2018-01-15 04:05
Duplicate of  #256

**Closed by silasary** 2018-01-15 04:05 UTC
